apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-1
spec:
  selector:
    matchLabels:
      app: app-demo-1
  replicas: 1
  template:
    metadata:
      labels:
        app: app-demo-1
    spec:
      volumes:
        - name: k8s-configmap-volume
          configMap:
            name: k8s-configmap   
      containers:
        - name: app-demo-1
          image: jeongminyeo/spring-boot-kubernetes-demo-service1
          volumeMounts:
            - mountPath: /etc/config
              name: k8s-configmap-volume
          ports:
            - containerPort: 8080
