apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-1
spec:
  selector:
    matchLabels:
      app: app-demo-1
  replicas: 1
  template:
    metadata:
      labels:
        app: app-demo-1
    spec:
      containers:
        - name: app-demo-1
          image: spring-boot-kubernetes-demo:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name:  app-demo
spec:
  selector:
    app:  app-demo
  type:  NodePort
  ports:
    - port: 8080
      targetPort: 8080
